[package]
name = "libsql_php_extension"
version = "0.1.0"
edition = "2021"

[lib]
name = "sql_php_extension"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
ext-php-rs = "*"
lazy_static = "1.4.0"
libsql = "0.3.5"
serde = { version = "1.0.199", features = ["derive"]}
serde_json = "1.0.116"
tokio = "1.37.0"
uuid = "1.8.0"

[profile.release]
strip="debuginfo"
