[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes software-properties-common",
    "add-apt-repository ppa:ondrej/php -y",
    "apt-get update",
    "apt-get install --assume-yes php8.3"
]
