[target.x86_64-unknown-linux-gnu]
dockerfile = "Dockerfile"

[target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-apple-darwin-cross:local"

[target.aarch64-unknown-linux-gnu]
image = ":edge"

[build]
rust-toolchain = "nightly"
